const form = document.querySelector('form#userForm')
const handleSubmit = function(ev) {
    ev.preventDefault
    const form = ev.target
    const userName = form.userName.value
const button = document.querySelector('button')

function changeText(){
let userInput = document.querySelector('.W');
userInput.textContent = document.getElementById("FS").value

} 
button.addEventListener('click', changeText)
}